// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ9PGoRmZPqOeYIpCLjsoEmO4d-FhRet8',
    appId: '1:719134124648:web:f1464a53f8095dba3ee9dd',
    messagingSenderId: '719134124648',
    projectId: 'chat-app-42e72',
    authDomain: 'chat-app-42e72.firebaseapp.com',
    storageBucket: 'chat-app-42e72.firebasestorage.app',
    measurementId: 'G-263JTJXR6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfBniLrLtyz-yt56bHscGrYZtvktPXQE',
    appId: '1:719134124648:android:7212a1d6f36a6a483ee9dd',
    messagingSenderId: '719134124648',
    projectId: 'chat-app-42e72',
    storageBucket: 'chat-app-42e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB05vzuRPShThWkdOO7588H3IHlrpZfXn0',
    appId: '1:719134124648:ios:635c9a3ac352e9ee3ee9dd',
    messagingSenderId: '719134124648',
    projectId: 'chat-app-42e72',
    storageBucket: 'chat-app-42e72.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB05vzuRPShThWkdOO7588H3IHlrpZfXn0',
    appId: '1:719134124648:ios:635c9a3ac352e9ee3ee9dd',
    messagingSenderId: '719134124648',
    projectId: 'chat-app-42e72',
    storageBucket: 'chat-app-42e72.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ9PGoRmZPqOeYIpCLjsoEmO4d-FhRet8',
    appId: '1:719134124648:web:4bf2b6c13c48df513ee9dd',
    messagingSenderId: '719134124648',
    projectId: 'chat-app-42e72',
    authDomain: 'chat-app-42e72.firebaseapp.com',
    storageBucket: 'chat-app-42e72.firebasestorage.app',
    measurementId: 'G-CV10X40RL4',
  );
}
